/**
 * THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.
 * 
 * Generated by @kelsny/synth v0.0.1 on 6/18/2022
 */

import { MaxConstraint, MinConstraint, RangeConstraint, RegexConstraint } from "./dist/core/validators/index.js";
import { ArrayNode, BigIntNode, BooleanNode, FunctionNode, LiteralNode, NoopNode, NullNode, NumberNode, ObjectNode, StringNode, SymbolNode, TupleNode, UndefinedNode, ValidationNode } from "./dist/core/providers/index.js";
import { Synthesized } from "./dist/core/synthesize.js";

// /Users/tht/Documents/projects/synth/examples/BinaryExpression.synth
export declare const BinaryExpression: Synthesized<ObjectNode<[["type", StringNode<false>, false], ["lhs", ObjectNode<[["type", LiteralNode<"CONSTANT">, false], ["value", NumberNode<false>, false]]>, false], ["rhs", ObjectNode<[["type", LiteralNode<"CONSTANT">, false], ["value", NumberNode<false>, false]]>, false]]>>

// /Users/tht/Documents/projects/synth/examples/CoordinatePair.synth
export declare const CoordinatePair: Synthesized<TupleNode<[NumberNode<false>, NumberNode<false>]>>

// /Users/tht/Documents/projects/synth/examples/Options.synth
export declare const Options: Synthesized<ObjectNode<[["type", SymbolNode, false], ["mode", StringNode<false>, false], ["dev", BooleanNode<false>, true], ["logLevel", NumberNode<false>, true], ["stdio", TupleNode<[StringNode<false>, StringNode<false>, StringNode<false>]>, true], ["override", ObjectNode<[[RegExp, BooleanNode<false>, false]]>, true]]>>

// /Users/tht/Documents/projects/synth/examples/PositiveNumber.synth
export declare const PositiveNumber: Synthesized<NumberNode<false>>

// /Users/tht/Documents/projects/synth/examples/ServerError.synth
export declare const ServerError: Synthesized<ObjectNode<[["code", NumberNode<false>, false], ["message", StringNode<false>, false]]>>